package com.example.rule_flow_log_expected;

/**
 * This class was automatically generated by the data modeler tool.
 */public class Fact implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String field1;
	private java.lang.String field2;

	private java.lang.String field3;

	private java.lang.String field4;

	public Fact() {
	}

	public java.lang.String getField1() {
		return this.field1;
	}

	public void setField1(java.lang.String field1) {
		this.field1 = field1;
	}

	public java.lang.String getField2() {
		return this.field2;
	}

	public void setField2(java.lang.String field2) {
		this.field2 = field2;
	}

	public java.lang.String getField3() {
		return this.field3;
	}

	public void setField3(java.lang.String field3) {
		this.field3 = field3;
	}

	public java.lang.String getField4() {
		return this.field4;
	}

	public void setField4(java.lang.String field4) {
		this.field4 = field4;
	}

	public Fact(java.lang.String field1, java.lang.String field2,
			java.lang.String field3, java.lang.String field4) {
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.field4 = field4;
	}
}